language: python
python:
  - "2.7"
  - "3.3"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - python setup.py build
    - python setup.py install
script:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then nosetests biggus; fi
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then cd build/lib/ && nosetests ; fi
